sudo: required

language: node_js
node_js:
  - node

branches:
  only:
    - master

cache:
  directories:
    - '$HOME/.npm'

install:
  - npm ci

script: npm run test:ci

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    on_success: never
    on_failure: change
