language: node_js
node_js:
    - "node"
branches:
    only:
        - master
        - /^greenkeeper-.*$/
cache: yarn
after_success: "cat ./tmp/coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
notifications:
    webhooks:
        urls:
            - https://aliem-slackbot.herokuapp.com/aliemu/hooks/travis-ci
        on_success: change
        on_failure: change
