language: nodejs
node_js:
    - "6"
before_script:
    - nvm install node
    - node --version
    - npm --version
    - nvm --version
    - npm install
script:
    - npm test
after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
notifications:
    slack:
        rooms:
            - alieminnovation:qbyg3p4KvNRgsAnZnqdgQaTD
        on_success: never
        on_failure: always
