version: '3'
services:
    wordpress:
        image: visiblevc/wordpress:0.17.0-php7.2
        ports:
            - 8080:80
        volumes:
            # Database
            - ./data:/data
            # Plugins
            - ./wp-content/plugins/learndash-propanel:/app/wp-content/plugins/learndash-propanel
            - ./wp-content/plugins/sfwd-lms:/app/wp-content/plugins/sfwd-lms
            - ./wp-content/plugins/ultimate-member:/app/wp-content/plugins/ultimate-member
            # Themes
            - ./dist/aliemu:/app/wp-content/themes/aliemu
            - ./wp-content/themes/Divi:/app/wp-content/themes/Divi
            # Uploads
            - ./wp-content/uploads:/app/wp-content/uploads
        environment:
            DB_NAME: wordpress
            URL_REPLACE: https://www.aliemu.com,http://localhost:8080
            SITE_NAME: aliemu.com
            DB_PASS: root
            DB_USER: root
            PLUGINS: >-
                academic-bloggers-toolkit,
                jetpack,
                mce-table-buttons,
                query-monitor,
                rest-api,
                sendgrid-email-delivery-simplified,
                w3-total-cache,
                wp-smushit,
                wpdiscuz,
                [Basic-Auth]https://github.com/WP-API/Basic-Auth/archive/master.zip,

                [ultimate-member]https://ultimatemember.com/wp-content/uploads/2017/11/ultimate-member.zip,
                [um-recaptcha]https://ultimatemember.com/wp-content/uploads/2017/11/um-recaptcha-2.0.zip,
            # Temporary until ultimate member 2.x lands on wordpress.org
            # ultimate-member,
            # [um-recaptcha]http://bit.ly/um-recaptcha,
            WP_DEBUG_LOG: 'true'
            WP_DEBUG_DISPLAY: 'true'
            WP_DEBUG: 'true'
    db:
        image: mariadb:10
        environment:
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - data:/var/lib/mysql
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            MYSQL_ROOT_PASSWORD: root
        ports:
            - 22222:80
volumes:
    data:
