version: '3.7'
services:
  wordpress:
    environment:
      URL_REPLACE: http://localhost:8080
      WP_DEBUG_DISPLAY: 'true'
      WP_DEBUG: 'true'
      WP_VERSION: nightly
      EXTRA_PHP: |
        define( 'ALIEM_API_KEY', '${ALIEM_API_KEY?ALIEM_API_KEY not defined in .env}' );
        define( 'RECAPTCHA_KEY', '${RECAPTCHA_KEY?RECAPTCHA_KEY not defined in .env}' );
        define( 'IMAGE_EDIT_OVERWRITE', true );
        define( 'SCRIPT_DEBUG', true );
        define( 'WP_DISABLE_FATAL_ERROR_HANDLER', true );
        define( 'WP_LOCAL_DEV', true );
        define( 'WP_POST_REVISIONS', 3 );
        if ( defined( 'WP_CLI' ) && WP_CLI && ! isset( $$_SERVER['HTTP_HOST'] ) ) {
            $$_SERVER['HTTP_HOST'] = 'localhost';
        }
      PLUGINS: >-
        academic-bloggers-toolkit
        [Basic-Auth]https://github.com/WP-API/Basic-Auth/archive/master.zip
        gutenberg
        jetpack
        query-monitor
        sendgrid-email-delivery-simplified
        ultimate-member
        w3-total-cache
    ports:
      - 8080:80
    volumes:
      - ./dist:/app/wp-content/themes/aliemu.com
      - ./scripts/on-init.sh:/on-init.sh
