version: '3'
services:
    wordpress:
        image: visiblevc/wordpress:0.18.0-php7.2
        environment:
            ALIEM_API_KEY: ${ALIEM_API_KEY?ALIEM_API_KEY key not defined in .env}
            DB_NAME: aliemu
            DB_PASS: root
            DB_USER: root
            PLUGINS: >-
                academic-bloggers-toolkit
                [Basic-Auth]https://github.com/WP-API/Basic-Auth/archive/master.zip
                jetpack
                mce-table-buttons
                query-monitor
                sendgrid-email-delivery-simplified
                ultimate-member
                [um-recaptcha]http://bit.ly/um-recaptcha
                w3-total-cache
                wordpress-seo
                wp-smushit
        volumes:
            - ./data:/data
            - ./wp-content/plugins/learndash-propanel:/app/wp-content/plugins/learndash-propanel
            - ./wp-content/plugins/sfwd-lms:/app/wp-content/plugins/sfwd-lms
            - ./wp-content/uploads:/app/wp-content/uploads
    db:
        image: mariadb:10
        environment:
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - data:/var/lib/mysql
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            MYSQL_ROOT_PASSWORD: root
        ports:
            - 22222:80
volumes:
    data:
